h2o:
    build: ./h2o
    ports:
        - "80:80"
    volumes:
        - ./h2o/log:/var/log/h2o
gitbucket:
    build: ./gitbucket
    ports:
        - "52201:52201"
    volumes:
        - ./gitbucket/data:/opt/gitbucket/data
        - ./gitbucket/log:/var/log/gitbucket
